$(function(){
    $('*').css({
        'margin':'0',
        'padding':'0'
    });
    $('body').css({
        'margin':'0 auto',
        'background':'#FCFBF9'
    });
    $('.container').css({
        'width':'300px',
        'height':'auto',
        'border':'solid 0px black',
        'position':'absolute'
    });
    $('.container2').css({
        'width':'1040px',
        'height':'auto',
        'border':'solid 0px black',
        'marginLeft':'310px',
        position:'absolute'
    });
    $('footer').css({
       'width':'100%',
        'height':'auto',
        'borderTop':'solid 0px gray',
        'marginTop':'10px',
        'background':'#430088',
        position:'absolute',
        marginTop:'1150px'
    });
    $('.menu').css({
        'width':'275px',
        'height':'auto',
        'border':'solid 1px #D4D5D7',
        'background':'#fff',
        'marginLeft':'10px',
        'marginTop':'10px'
    });
    $('.header').css({
        'width':'275px',
        'height':'50px',
        'border':'solid 0px #D4D5D7',
        'background':'#430088',
        'marginLeft':'10px',
        'marginTop':'10px',
        color:'white',
        fontSize:'40px',
        fontFamily:'Blessed Day',
        textAlign:'center'
    });
    $('.searchdiv').css({
        'width':'275px',
        'height':'50px',
        'border':'solid 0px #D4D5D7',
        'marginLeft':'10px',
        'marginTop':'10px',
        textAlign:'center'
    });
    $('.txtsearch').css({
        width:'220px',
        height:'30px',
        paddingLeft:'10px'
    });
    $('.btnsearch').css({
        width:'50px',
        height:'30px',
        marginLeft:'-5px',
        marginTop:'10px',
        border:'solid 0px #430088',
        background:'#430088',
        color:'white',
        boxShadow:'0px 0px 0px 0px black'
    });
    $('.new').css({
        'width':'710px',
        'height':'310px',
        'border':'solid 1px #D1A33D',
        'marginTop':'10px',
        'position':'absolute'
    });
    $('.imgnew').css({
        'width':'100%',
        'height':'308px'
    });
    $('.ketnew').css({
        position:'absolute',
        background:'rgba(225,200,000,.5)',
        width:'300px',
        height:'308px',
        marginTop:'-308px',
    });
    $('.newtitle').css({
        fontFamily:'Idealist Sans',
        fontSize:'20px',
        color:'white',
        textAlign:'center', 
    });
    $('.newtitle').eq(1).css({
        fontSize:'15px',
        textAlign:'left',
        paddingLeft:'10px',
        fontFamily:'arial'
    });
    $('.btnnew').css({
        background:'rgba(0,0,0,0.5)',
        border:'0',
        width:'100px',
        border:'solid 0px white',
        height:'25px',
        borderRadius:'5px',
        fontSize:'13px'
    });
    $('.btnnew').mouseenter(function(){
        $('.btnnew').css({
            background:'rgba(225,225,225,.8)',
            transition:'all 0.3s',
            color:'black'
        });
    });
    $('.btnnew').mouseleave(function(){
        $('.btnnew').css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btndownloadnew').css({
        border:'0',
        width:'50px',
        height:'50px',
        borderRadius:'50%',
        background:'rgba(0,0,0,.5)',
    });
    $('.btndownloadnew').eq(0).mouseenter(function(){
        $('.btndownloadnew').eq(0).css({
            background:'rgba(225,225,225,.8)',
            transition:'all 0.3s',
            color:'black'
        });
    });
    $('.btndownloadnew').eq(0).mouseleave(function(){
        $('.btndownloadnew').eq(0).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btndownloadnew').eq(1).mouseenter(function(){
        $('.btndownloadnew').eq(1).css({
            background:'rgba(225,225,225,.8)',
            transition:'all 0.3s',
            color:'black'
        });
    });
    $('.btndownloadnew').eq(1).mouseleave(function(){
        $('.btndownloadnew').eq(1).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btndownloadnew').eq(2).mouseenter(function(){
        $('.btndownloadnew').eq(2).css({
            background:'rgba(225,225,225,.8)',
            transition:'all 0.3s',
            color:'black'
        });
    });
    $('.btndownloadnew').eq(2).mouseleave(function(){
        $('.btndownloadnew').eq(2).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btndownloadnew').eq(3).mouseenter(function(){
        $('.btndownloadnew').eq(3).css({
            background:'rgba(225,225,225,.8)',
            transition:'all 0.3s',
            color:'black'
        });
    });
    $('.btndownloadnew').eq(3).mouseleave(function(){
        $('.btndownloadnew').eq(3).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btndownloadnew').eq(4).mouseenter(function(){
        $('.btndownloadnew').eq(4).css({
            background:'rgba(225,225,225,.8)',
            transition:'all 0.3s',
            color:'black'
        });
    });
    $('.btndownloadnew').eq(4).mouseleave(function(){
        $('.btndownloadnew').eq(4).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.containernew').css({
        width:'318px',
        height:'310px',
        border:'solid 0px black',
        marginLeft:'720px',
        marginTop:'10px',
        
    });
    $('.new2').eq(0).css({
        width:'150px',
        height:'150px',
        marginLeft:'0px',
        position:'absoute',
        marginTop:'0px',
        border:'solid 1px #95948F',
    });
    $('.new2').eq(1).css({
        border:'solid 1px #FF7B00',
        width:'150px',
        height:'150px',
        marginTop:'-150px',
        marginLeft:'160px'
    });
    $('.new2').eq(2).css({
        marginLeft:'0px',
        border:'solid 1px #4C5700',
        marginTop:'10px',
        width:'150px',
        height:'150px',
    });
    $('.new2').eq(3).css({
        marginLeft:'160px',
        marginTop:'-150px',
        width:'150px',
        height:'150px',
        border:'solid 1px black',
    });
    $('.ketnew2').css({
        position:'absolute',
        width:'148px',
        height:'100px',
        background:'rgba(200,200,150,.5)',
        marginTop:'-100px',
        color:'white',
        paddingLeft:'5px',
        textAlign:'center',
        paddingTop:'30px'
    });
    $('.imgnew2').css({
        width:'100%',
        height:'100%'
    });
    $('.ketnew2').eq(1).css({
        background:'rgba(180,100,0,.5)',
    });
    $('.ketnew2').eq(2).css({
        background:'rgba(100,150,50,.5)',
    });
    $('.ketnew2').eq(3).css({
        background:'rgba(250,0,0,.5)',
    });
    $('.btnketnew2').css({
       width:'100px',
        height:'27px',
        border:'0',
        fontSize:'13px',
        background:'rgba(0,0,0,0.5)',
        fontWeight:'normal'
    });
    $('.btnketnew2').eq(0).mouseenter(function(){
        $('.btnketnew2').eq(0).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(0).mouseleave(function(){
        $('.btnketnew2').eq(0).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(1).mouseenter(function(){
        $('.btnketnew2').eq(1).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(1).mouseleave(function(){
        $('.btnketnew2').eq(1).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(2).mouseenter(function(){
        $('.btnketnew2').eq(2).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(2).mouseleave(function(){
        $('.btnketnew2').eq(2).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(3).mouseenter(function(){
        $('.btnketnew2').eq(3).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(3).mouseleave(function(){
        $('.btnketnew2').eq(3).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(4).mouseenter(function(){
        $('.btnketnew2').eq(4).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(4).mouseleave(function(){
        $('.btnketnew2').eq(4).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(5).mouseenter(function(){
        $('.btnketnew2').eq(5).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(5).mouseleave(function(){
        $('.btnketnew2').eq(5).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(6).mouseenter(function(){
        $('.btnketnew2').eq(6).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(6).mouseleave(function(){
        $('.btnketnew2').eq(6).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(7).mouseenter(function(){
        $('.btnketnew2').eq(7).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(7).mouseleave(function(){
        $('.btnketnew2').eq(7).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(8).mouseenter(function(){
        $('.btnketnew2').eq(8).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(8).mouseleave(function(){
        $('.btnketnew2').eq(8).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(9).mouseenter(function(){
        $('.btnketnew2').eq(9).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(9).mouseleave(function(){
        $('.btnketnew2').eq(9).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(10).mouseenter(function(){
        $('.btnketnew2').eq(10).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(10).mouseleave(function(){
        $('.btnketnew2').eq(10).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(11).mouseenter(function(){
        $('.btnketnew2').eq(11).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(11).mouseleave(function(){
        $('.btnketnew2').eq(11).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(12).mouseenter(function(){
        $('.btnketnew2').eq(12).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(12).mouseleave(function(){
        $('.btnketnew2').eq(12).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(13).mouseenter(function(){
        $('.btnketnew2').eq(13).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(13).mouseleave(function(){
        $('.btnketnew2').eq(13).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(14).mouseenter(function(){
        $('.btnketnew2').eq(14).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(14).mouseleave(function(){
        $('.btnketnew2').eq(14).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(15).mouseenter(function(){
        $('.btnketnew2').eq(15).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(15).mouseleave(function(){
        $('.btnketnew2').eq(15).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(16).mouseenter(function(){
        $('.btnketnew2').eq(16).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(16).mouseleave(function(){
        $('.btnketnew2').eq(16).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(17).mouseenter(function(){
        $('.btnketnew2').eq(17).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(17).mouseleave(function(){
        $('.btnketnew2').eq(17).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(18).mouseenter(function(){
        $('.btnketnew2').eq(18).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(18).mouseleave(function(){
        $('.btnketnew2').eq(18).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(19).mouseenter(function(){
        $('.btnketnew2').eq(19).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(19).mouseleave(function(){
        $('.btnketnew2').eq(19).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(20).mouseenter(function(){
        $('.btnketnew2').eq(20).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(20).mouseleave(function(){
        $('.btnketnew2').eq(20).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(21).mouseenter(function(){
        $('.btnketnew2').eq(21).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(21).mouseleave(function(){
        $('.btnketnew2').eq(21).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(22).mouseenter(function(){
        $('.btnketnew2').eq(22).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(22).mouseleave(function(){
        $('.btnketnew2').eq(22).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(23).mouseenter(function(){
        $('.btnketnew2').eq(23).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(23).mouseleave(function(){
        $('.btnketnew2').eq(23).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(24).mouseenter(function(){
        $('.btnketnew2').eq(24).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(24).mouseleave(function(){
        $('.btnketnew2').eq(24).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(25).mouseenter(function(){
        $('.btnketnew2').eq(25).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(25).mouseleave(function(){
        $('.btnketnew2').eq(25).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(26).mouseenter(function(){
        $('.btnketnew2').eq(26).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(26).mouseleave(function(){
        $('.btnketnew2').eq(26).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.btnketnew2').eq(27).mouseenter(function(){
        $('.btnketnew2').eq(27).css({
            transition:'all 0.3s',
            background:'rgba(225,225,225,.8)',
            color:'black'
        });
    });
    $('.btnketnew2').eq(27).mouseleave(function(){
        $('.btnketnew2').eq(27).css({
            background:'rgba(0,0,0,0.5)',
            color:'white'
        });
    });
    $('.subcontain').css({
        width:'160px',
        height:'180px',
        marginTop:'10px',
        position:'absolute',
    });
    $('.subcontain2').css({
        width:'160px',
        height:'180px',
        position:'absolute',
        marginLeft:'175px',
        marginTop:'10px',
    });
    $('.subcontain3').css({
        width:'160px',
        height:'180px',
        position:'absolute',
        marginTop:'10px',
        marginLeft:'350px',
    });
    $('.subcontain4').css({
        width:'160px',
        height:'180px',
        marginTop:'10px',
        position:'absolute',
        marginLeft:'523px',
    });
    $('.subcontain5').css({
        width:'160px',
        height:'180px',
        position:'absolute',
        marginTop:'10px',
        marginLeft:'697px',
    });
    $('.subcontain6').css({
        width:'160px',
        height:'180px',
        position:'relative',
        marginTop:'10px',
        marginLeft:'870px',
    });
    $('.subcontain6').eq(3).css({
        marginBottom:'17px'
    });
    $('.subcontain7').css({
        width:'400px',
        margin:'0 auto',
        height:'40px',
        background:'green',
        marginBottom:'10px',
        'background':'#FCFBF9',
        'border':'solid 1px gray',
        borderRadius:'5px'
    });
    $('td').css({
        width:'40px',
        borderRight:'solid 1px gray',
        height:'38px',
        textAlign:'center',
        fontSize:'15px',
        color:'black',
        background:'#fff'
    });
    $('td').first().css({
        borderRadius:'3px 0px 0px 3px'
    });
    $('td').last().css({
        border:'0',
        borderRadius:'0px 3px 3px 0px'
    });
    $('td').eq(1).css({
        background:'#430088',
        color:'white'
    });
    $('td').eq(0).mouseenter(function(){
        $('td').eq(0).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(0).mouseleave(function(){
        $('td').eq(0).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(1).mouseenter(function(){
        $('td').eq(1).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(1).mouseleave(function(){
        $('td').eq(1).css({
            background:'#430088',
            color:'white'
        });
    });
    $('td').eq(2).mouseenter(function(){
        $('td').eq(2).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(2).mouseleave(function(){
        $('td').eq(2).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(3).mouseenter(function(){
        $('td').eq(3).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(3).mouseleave(function(){
        $('td').eq(3).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(4).mouseenter(function(){
        $('td').eq(4).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(4).mouseleave(function(){
        $('td').eq(4).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(5).mouseenter(function(){
        $('td').eq(5).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(5).mouseleave(function(){
        $('td').eq(5).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(6).mouseenter(function(){
        $('td').eq(6).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(6).mouseleave(function(){
        $('td').eq(6).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(7).mouseenter(function(){
        $('td').eq(7).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(7).mouseleave(function(){
        $('td').eq(7).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(8).mouseenter(function(){
        $('td').eq(8).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(8).mouseleave(function(){
        $('td').eq(8).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(9).mouseenter(function(){
        $('td').eq(9).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(9).mouseleave(function(){
        $('td').eq(9).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(10).mouseenter(function(){
        $('td').eq(10).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(10).mouseleave(function(){
        $('td').eq(10).css({
            background:'#fff',
            color:'black'
        });
    });
    $('td').eq(11).mouseenter(function(){
        $('td').eq(11).css({
            background:'#430088',
            transition:'all 0.3s',
            color:'white'
        });
    });
    $('td').eq(11).mouseleave(function(){
        $('td').eq(11).css({
            background:'#fff',
            color:'black'
        });
    });
    $('.subconimg').css({
        width:'100%',
        height:'100%',
    });
    $('.ketsubconimg').css({
        width:'160px',
        height:'120px',
        position:'absolute',
        
        marginTop:'-120px',
        color:'white',
        paddingLeft:'5px',
        textAlign:'center',
        paddingTop:'30px',
        fontWeight:'bold'
    });
    $('.ketsubconimg').eq(0).css({
        background:'rgba(0,160,160,.6)',
    });
    $('.ketsubconimg').eq(1).css({
        background:'rgba(250,100,0,.5)'
    });
    $('.ketsubconimg').eq(2).css({
        background:'rgba(0,80,250,.5)'
    });
    $('.ketsubconimg').eq(3).css({
        background:'rgba(225,225,225,.5)'
    });
    $('.ketsubconimg').eq(4).css({
        background:'rgba(0,60,200,.5)'
    });
    $('.ketsubconimg').eq(5).css({
        background:'rgba(150,200,100,.5)'
    });
    $('.ketsubconimg').eq(6).css({
        background:'rgba(50,0,0,.5)'
    });
    $('.ketsubconimg').eq(7).css({
        background:'rgba(160,140,0,.5)'
    });
    $('.ketsubconimg').eq(8).css({
        background:'rgba(0,0,50,.5)'
    });
    $('.ketsubconimg').eq(9).css({
        background:'rgba(120,100,0,.5)'
    });
    $('.ketsubconimg').eq(10).css({
        background:'rgba(0,100,150,.5)'
    });
    $('.ketsubconimg').eq(11).css({
        background:'rgba(0,0,0,.5)'
    });
    $('.ketsubconimg').eq(12).css({
        background:'rgba(100,0,0,.5)'
    });
    $('.ketsubconimg').eq(13).css({
        background:'rgba(50,70,50,.5)'
    });
    $('.ketsubconimg').eq(14).css({
        background:'rgba(100,160,150,.6)',
    });
    $('.ketsubconimg').eq(15).css({
        background:'rgba(0,120,50,.5)'
    });
    $('.ketsubconimg').eq(16).css({
        background:'rgba(90,50,20,.5)'
    });
    $('.ketsubconimg').eq(17).css({
        background:'rgba(10,120,200,.5)'
    });
    $('.ketsubconimg').eq(18).css({
        background:'rgba(200,50,50,.5)'
    });
    $('.ketsubconimg').eq(19).css({
        background:'rgba(50,0,200,.5)'
    });
    $('.ketsubconimg').eq(20).css({
        background:'rgba(100,100,100,.5)'
    });
    $('.ketsubconimg').eq(21).css({
        background:'rgba(150,0,0,.5)'
    });
    $('.ketsubconimg').eq(22).css({
        background:'rgba(90,0,100,.5)'
    });
    $('.ketsubconimg').eq(23).css({
        background:'rgba(90,200,100,.5)'
    });
    $('.pmenu').css({
        width:'100%',
        height:'30px',
        background:'#430088',
        color:'white',
        paddingTop:'7px',
        paddingLeft:'10px',
        fontSize:'13px',
    });
    $('.home').css({
        marginLeft:'95px'
    });
    $('.home').eq(1).css({
        marginLeft:'60px'
    });
    $('.home').eq(2).css({
        marginLeft:'30px'
    });
    $('.lain').css({
        marginLeft:'20px'
    });
    $('.pmenu').eq(1).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(2).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(3).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(4).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(5).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(6).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(7).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(8).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(9).css({
        background:'#fff',
        color:'gray'
    });
    $('.pmenu').eq(1).mouseenter(function(){
        $('.pmenu').eq(1).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(1).mouseleave(function(){
        $('.pmenu').eq(1).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(2).mouseenter(function(){
        $('.pmenu').eq(2).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(2).mouseleave(function(){
        $('.pmenu').eq(2).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(3).mouseenter(function(){
        $('.pmenu').eq(3).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(3).mouseleave(function(){
        $('.pmenu').eq(3).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(4).mouseenter(function(){
        $('.pmenu').eq(4).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(4).mouseleave(function(){
        $('.pmenu').eq(4).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(5).mouseenter(function(){
        $('.pmenu').eq(5).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(5).mouseleave(function(){
        $('.pmenu').eq(5).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(6).mouseenter(function(){
        $('.pmenu').eq(6).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(6).mouseleave(function(){
        $('.pmenu').eq(6).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(7).mouseenter(function(){
        $('.pmenu').eq(7).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(7).mouseleave(function(){
        $('.pmenu').eq(7).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(8).mouseenter(function(){
        $('.pmenu').eq(8).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(8).mouseleave(function(){
        $('.pmenu').eq(8).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.pmenu').eq(9).mouseenter(function(){
        $('.pmenu').eq(9).css({
            background:'#430088',
            color:'white',
            transition:'all 0.3s',
            borderTop:'solid 1px #9680AB'
        });
    });
    $('.pmenu').eq(9).mouseleave(function(){
        $('.pmenu').eq(9).css({
            background:'white',
            color:'#9680AB',
            border:'0'
        });
    });
    $('.top').css({
        'width':'275px',
        'height':'auto',
        'border':'solid 1px #D4D5D7',
        'background':'#fff',
        'marginLeft':'10px',
        'marginTop':'10px'
    });
    $('.top').eq(2).css({
        'width':'275px',
        'height':'100px',
        'border':'solid 1px #D4D5D7',
        'background':'#fff',
        'marginLeft':'10px',
        'marginTop':'10px',
        paddingTop:'5px',
        paddingLeft:'0px',
        textAlign:'center',
        fontFamily:'Idealist Sans',
        fontSize:'20px'
    });
    $('.imgtop').css({
        width:'100%',
        height:'170px'
    });
    $('.imgtop').eq(1).css({
        width:'135px',
        height:'80px',
        marginTop:'2px'
    });
    $('.imgtop').eq(2).css({
        width:'136px',
        height:'80px',
        marginTop:'2px',
        marginLeft:'-2px'
    });
    $('.imgsof').css({
        width:'135px',
        height:'80px',
        marginTop:'2px'
    });
    $('.imgsof').eq(1).css({
        width:'136px',
        height:'80px',
        marginTop:'2px',
        marginLeft:'-2px'
    });
    $('.cod').css({
        background:'rgba(50,0,200,.4)',
        width:'170px',
        height:'50px',
        position:'absolute',
        marginTop:'-100px',
        fontSize:'17px',
        fontFamily:'idealist Sans',
        paddingTop:'11px',
        color:'white',
        textAlign:'center'
    });
    $('.cod').eq(1).css({
        fontSize:'12px'
    });
    $('.ds').css({
        background:'rgba(50,0,200,.4)',
        width:'90px',
        height:'40px',
        position:'absolute',
        marginTop:'-50px',
        fontSize:'11px',
        fontFamily:'idealist Sans',
        paddingTop:'11px',
        color:'white',
        textAlign:'center'
    });
    $('.dl').css({
        background:'rgba(50,0,200,.4)',
        width:'90px',
        height:'40px',
        position:'absolute',
        marginTop:'-50px',
        fontSize:'11px',
        fontFamily:'idealist Sans',
        paddingTop:'12px',
        color:'white',
        textAlign:'center',
        marginLeft:'140px'
    });
    $('.ketfooter').css({
        width:'250px',
        height:'auto',
        border:'solid 0px black',
        marginTop:'10px',
        marginLeft:'280px',
        position:'absolute',
        marginBottom:'10px',
        borderRight:'solid 1px white'
    });
    $('.ketfooter').eq(1).css({
        marginLeft:'555px'
    });
    $('.ketfooter').eq(2).css({
        marginLeft:'830px',
        position:'relative',
        
    });
    $('.pkfooter').css({
        width:'100%',
        height:'30px',
        background:'#fff',
        color:'#000',
        paddingTop:'7px',
        paddingLeft:'10px',
        fontSize:'13px',
        textAlign:'center'
    });
    $('.tdgame').css({
        width:'160px',
        height:'20px',
        borderRadius:'0',
        border:'0',
        fontSize:'13px',
        background:'#430088',
        color:'white',
        textAlign:'left',
        paddingLeft:'5px'
    });
    $('.tdgame1').css({
        width:'80px',
        height:'20px',
        borderRadius:'0',
        border:'0',
        fontSize:'13px',
        color:'white',
        background:'#430088',
        textAlign:'right',
        paddingRight:'0px'
    });
    $('.copyright').css({
        color:'white',
        fontFamily:'tahoma',
        fontSize:'13px',
        textAlign:'center'
    });
});